- name: Retrieve container log
  distronode.builtin.command:
    cmd: >-
      {% raw %}
      podman logs
      {% endraw %}
      {{ item.stdout_lines[0] }}
    # podman inspect --format='{{.HostConfig.LogConfig.Path}}'
  changed_when: false
  register: logfile_cmd

- name: Display container log
  distronode.builtin.fail:
    msg: "{{ logfile_cmd.stderr }}"
