- name: Retrieve container log
  distronode.builtin.command:
    cmd: >-
      {% raw %}
      docker logs
      {% endraw %}
      {{ item.stdout_lines[0] }}
  changed_when: false
  register: logfile_cmd

- name: Display container log
  distronode.builtin.fail:
    msg: "{{ logfile_cmd.stderr }}"
